["github.com/alecthomas/assert"]
  sumVersion = "v0.0.0-20170929043011-405dbfeb8e38"
  ["github.com/alecthomas/assert".fetch]
    type = "git"
    url = "https://github.com/alecthomas/assert"
    rev = "405dbfeb8e38effee6e723317226e93fff912d06"
    sha256 = "1l567pi17k593nrd1qlbmiq8z9jy3qs60px2a16fdpzjsizwqx8l"

["github.com/alecthomas/chroma"]
  sumVersion = "v0.10.0"
  ["github.com/alecthomas/chroma".fetch]
    type = "git"
    url = "https://github.com/alecthomas/chroma"
    rev = "36bdd4b98823bd1d7be96767cde3dd575e60b406"
    sha256 = "0hjzb61m5lzx95xss82wil9s8f9hbw1zb3jj73ljfwkq5lqk76zq"

["github.com/alecthomas/colour"]
  sumVersion = "v0.0.0-20160524082231-60882d9e2721"
  ["github.com/alecthomas/colour".fetch]
    type = "git"
    url = "https://github.com/alecthomas/colour"
    rev = "60882d9e27213e8552dcff6328914fe4c2b44bc9"
    sha256 = "0iq566534gbzkd16ixg7fk298wd766821vvs80838yifx9yml5vs"

["github.com/alecthomas/kong"]
  sumVersion = "v0.2.4"
  ["github.com/alecthomas/kong".fetch]
    type = "git"
    url = "https://github.com/alecthomas/kong"
    rev = "109dce7ea5d32e63a96a2c234e991ea3ea470e77"
    sha256 = "0lv8xk71p5729igwmp6slhmf9x1g5z3zmkfx1mg1y2spn2ck4q7l"

["github.com/alecthomas/repr"]
  sumVersion = "v0.0.0-20180818092828-117648cd9897"
  ["github.com/alecthomas/repr".fetch]
    type = "git"
    url = "https://github.com/alecthomas/repr"
    rev = "117648cd9897bc621d6d52cd05727b9abdd5528a"
    sha256 = "05v1rgzdqc8razf702laagrvhvx68xd9yxxmzd3dyz0d6425pdrp"

["github.com/aymerick/douceur"]
  sumVersion = "v0.2.0"
  ["github.com/aymerick/douceur".fetch]
    type = "git"
    url = "https://github.com/aymerick/douceur"
    rev = "c5c95ec357c8235fbd7f34e8c843d36783f3fad9"
    sha256 = "1hfysznib0fqbp8vqxpk0xiggpp0ayk2bsddi36vbg6f8zq5f81n"

["github.com/charmbracelet/glamour"]
  sumVersion = "v0.5.0"
  ["github.com/charmbracelet/glamour".fetch]
    type = "git"
    url = "https://github.com/charmbracelet/glamour"
    rev = "94148ad4a6abc63b3aa2a4aa915dc2031716009e"
    sha256 = "18g93p116rwqh8yl0zf32gq6jfbjwmp6ybn8nkh9fpzh5grhh6n9"

["github.com/chris-ramon/douceur"]
  sumVersion = "v0.2.0"
  ["github.com/chris-ramon/douceur".fetch]
    type = "git"
    url = "https://github.com/chris-ramon/douceur"
    rev = "c5c95ec357c8235fbd7f34e8c843d36783f3fad9"
    sha256 = "1hfysznib0fqbp8vqxpk0xiggpp0ayk2bsddi36vbg6f8zq5f81n"

["github.com/danwakefield/fnmatch"]
  sumVersion = "v0.0.0-20160403171240-cbb64ac3d964"
  ["github.com/danwakefield/fnmatch".fetch]
    type = "git"
    url = "https://github.com/danwakefield/fnmatch"
    rev = "cbb64ac3d964b81592e64f957ad53df015803288"
    sha256 = "0cbf511ppsa6hf59mdl7nbyn2b2n71y0bpkzbmfkdqjhanqh1lqz"

["github.com/davecgh/go-spew"]
  sumVersion = "v1.1.1"
  ["github.com/davecgh/go-spew".fetch]
    type = "git"
    url = "https://github.com/davecgh/go-spew"
    rev = "8991bc29aa16c548c550c7ff78260e27b9ab7c73"
    sha256 = "0hka6hmyvp701adzag2g26cxdj47g21x6jz4sc6jjz1mn59d474y"

["github.com/dlclark/regexp2"]
  sumVersion = "v1.4.0"
  ["github.com/dlclark/regexp2".fetch]
    type = "git"
    url = "https://github.com/dlclark/regexp2"
    rev = "955551b554999d8e80dba0184eab21e642786508"
    sha256 = "1irfv89b7lfkn7k3zgx610ssil6k61qs1wjj31kvqpxb3pdx4kry"

["github.com/gorilla/css"]
  sumVersion = "v1.0.0"
  ["github.com/gorilla/css".fetch]
    type = "git"
    url = "https://github.com/gorilla/css"
    rev = "398b0b046082ecb3694c01bec6b336a06a4e530a"
    sha256 = "116fhy3n7bsq3psyn4pa0i4x9zy916kh1zxslmbbp0p9l4i7ysrj"

["github.com/lucasb-eyer/go-colorful"]
  sumVersion = "v1.2.0"
  ["github.com/lucasb-eyer/go-colorful".fetch]
    type = "git"
    url = "https://github.com/lucasb-eyer/go-colorful"
    rev = "d2b05a0d83cca9d610425691c3253d5f36d0ad06"
    sha256 = "08c3fkf27r16izjjd4w94xd1z7w1r4mdalbl53ms2ka2j465s3qs"

["github.com/mattn/go-colorable"]
  sumVersion = "v0.1.6"
  ["github.com/mattn/go-colorable".fetch]
    type = "git"
    url = "https://github.com/mattn/go-colorable"
    rev = "68e95eba382c972aafde02ead2cd2426a8a92480"
    sha256 = "0zv9ix7g0qf71jdhv7gbab9hjfkgbxl22kwhpz9ck1y6m4g1zxaw"

["github.com/mattn/go-isatty"]
  sumVersion = "v0.0.14"
  ["github.com/mattn/go-isatty".fetch]
    type = "git"
    url = "https://github.com/mattn/go-isatty"
    rev = "504425e14f742f1f517c4586048b49b37f829c8e"
    sha256 = "015zc3j60vb85d7f2al15la24wn45piazxlagqhzrbgfdyqci60z"

["github.com/mattn/go-runewidth"]
  sumVersion = "v0.0.13"
  ["github.com/mattn/go-runewidth".fetch]
    type = "git"
    url = "https://github.com/mattn/go-runewidth"
    rev = "df1ff59654317c1b5a3f860ffc47402931932104"
    sha256 = "1yir0f3wc5z5hnkwhvx5qb6nmpfb05zp2gvfjvna63s8kmla1rrn"

["github.com/microcosm-cc/bluemonday"]
  sumVersion = "v1.0.18"
  ["github.com/microcosm-cc/bluemonday".fetch]
    type = "git"
    url = "https://github.com/microcosm-cc/bluemonday"
    rev = "078c4be36c026823b61584e09e7d44f1d2139566"
    sha256 = "1pwwa1xb6qgg2dxpfwgy7q4m0dcs99cjz61qaxb3rkicv365icwy"

["github.com/muesli/reflow"]
  sumVersion = "v0.3.0"
  ["github.com/muesli/reflow".fetch]
    type = "git"
    url = "https://github.com/muesli/reflow"
    rev = "602e329532049c9e33fa8c74e352a46fb9486947"
    sha256 = "09zcz2cqdwgj1ilya5pqwndryk6lansn87x63fcm8j1xn74vd2ry"

["github.com/muesli/termenv"]
  sumVersion = "v0.11.0"
  ["github.com/muesli/termenv".fetch]
    type = "git"
    url = "https://github.com/muesli/termenv"
    rev = "800457db50d031051266bb7b233b69b367a1f571"
    sha256 = "0dqvk46f6bpnkdj3dq70cwvgn1g59z3my24d0l49xvrjqirq1iv7"

["github.com/olekukonko/tablewriter"]
  sumVersion = "v0.0.5"
  ["github.com/olekukonko/tablewriter".fetch]
    type = "git"
    url = "https://github.com/olekukonko/tablewriter"
    rev = "c7d2a8a09b076b70918308a3cd95464b2ae3b5d8"
    sha256 = "0zhnrih2px6jm8nxzkz8s7va3lj03bzwxim8wjba9zh7i78bp67z"

["github.com/pkg/errors"]
  sumVersion = "v0.9.1"
  ["github.com/pkg/errors".fetch]
    type = "git"
    url = "https://github.com/pkg/errors"
    rev = "614d223910a179a466c1767a985424175c39b465"
    sha256 = "1761pybhc2kqr6v5fm8faj08x9bql8427yqg6vnfv6nhrasx1mwq"

["github.com/pmezard/go-difflib"]
  sumVersion = "v1.0.0"
  ["github.com/pmezard/go-difflib".fetch]
    type = "git"
    url = "https://github.com/pmezard/go-difflib"
    rev = "792786c7400a136282c1664665ae0a8db921c6c2"
    sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw"

["github.com/rivo/uniseg"]
  sumVersion = "v0.2.0"
  ["github.com/rivo/uniseg".fetch]
    type = "git"
    url = "https://github.com/rivo/uniseg"
    rev = "75711fccf6a3e85bc74c241e2dddd06a9bc9e53d"
    sha256 = "0j7h22vfmjj562vr8gpsyrkrwp1pq9ayh5fylv24skxb467g9f0q"

["github.com/sergi/go-diff"]
  sumVersion = "v1.0.0"
  ["github.com/sergi/go-diff".fetch]
    type = "git"
    url = "https://github.com/sergi/go-diff"
    rev = "1744e2970ca51c86172c8190fadad617561ed6e7"
    sha256 = "0swiazj8wphs2zmk1qgq75xza6m19snif94h2m6fi8dqkwqdl7c7"

["github.com/stretchr/objx"]
  sumVersion = "v0.1.0"
  ["github.com/stretchr/objx".fetch]
    type = "git"
    url = "https://github.com/stretchr/objx"
    rev = "facf9a85c22f48d2f52f2380e4efce1768749a89"
    sha256 = "19ynspzjdynbi85xw06mh8ad5j0qa1vryvxjgvbnyrr8rbm4vd8w"

["github.com/stretchr/testify"]
  sumVersion = "v1.7.0"
  ["github.com/stretchr/testify".fetch]
    type = "git"
    url = "https://github.com/stretchr/testify"
    rev = "acba37e5db06f0093b465a7d47822bf13644b66c"
    sha256 = "0ixgjsvafr3513pz3r6pmgk074s2dxkll0dadvl25gkf30rkmh10"

["github.com/yuin/goldmark"]
  sumVersion = "v1.4.7"
  ["github.com/yuin/goldmark".fetch]
    type = "git"
    url = "https://github.com/yuin/goldmark"
    rev = "1def545b062947ba8c394c6553b5324b53af1e97"
    sha256 = "0frcl5g06vbvcj6zzvwjsl13nkmhh2n8109dkp18mq78f459ax4p"

["github.com/yuin/goldmark-emoji"]
  sumVersion = "v1.0.1"
  ["github.com/yuin/goldmark-emoji".fetch]
    type = "git"
    url = "https://github.com/yuin/goldmark-emoji"
    rev = "0faf8bc2325ac2955c586e3349de258db83c433c"
    sha256 = "0jl0w0hnfhfm4wvlxbbkyzfxyr9sk8q0nxaydql6wq64my5h49ln"

["golang.org/x/net"]
  sumVersion = "v0.0.0-20220127200216-cd36cc0744dd"
  ["golang.org/x/net".fetch]
    type = "git"
    url = "https://go.googlesource.com/net"
    rev = "cd36cc0744dd695657988f15f08446dc81e16efc"
    sha256 = "1gkddgbhl0hkx79y31pfr2a7qc1wnviwmzfzh722sngck0cqd61h"

["golang.org/x/sys"]
  sumVersion = "v0.0.0-20220224003255-dbe011f71a99"
  ["golang.org/x/sys".fetch]
    type = "git"
    url = "https://go.googlesource.com/sys"
    rev = "dbe011f71a99a3a1db8c5ee69896cd929128da6f"
    sha256 = "1wcbbcdvv4dwarcq5a8551fh2593r2hsx4frnxxb8avanmdps1v4"

["golang.org/x/term"]
  sumVersion = "v0.0.0-20210927222741-03fcf44c2211"
  ["golang.org/x/term".fetch]
    type = "git"
    url = "https://go.googlesource.com/term"
    rev = "03fcf44c2211dcd5eb77510b5f7c1fb02d6ded50"
    sha256 = "0aw5lgwq5w5kvwfa3jl7l83p9c827ksy4a99dqzzsqxvmk2zdi8f"

["golang.org/x/text"]
  sumVersion = "v0.3.7"
  ["golang.org/x/text".fetch]
    type = "git"
    url = "https://go.googlesource.com/text"
    rev = "383b2e75a7a4198c42f8f87833eefb772868a56f"
    sha256 = "0xkw0qvfjyifdqd25y7nxdqkdh92inymw3q7841nricc9s01p4jy"

["golang.org/x/tools"]
  sumVersion = "v0.0.0-20180917221912-90fa682c2a6e"
  ["golang.org/x/tools".fetch]
    type = "git"
    url = "https://go.googlesource.com/tools"
    rev = "90fa682c2a6e6a37b3a1364ce2fe1d5e41af9d6d"
    sha256 = "03ic2xsy51jw9749wl7gszdbz99iijbd2bckgygl6cm9w5m364ak"

["gopkg.in/check.v1"]
  sumVersion = "v0.0.0-20161208181325-20d25e280405"
  ["gopkg.in/check.v1".fetch]
    type = "git"
    url = "https://gopkg.in/check.v1"
    rev = "20d25e2804050c1cd24a7eea1e7a6447dd0e74ec"
    sha256 = "0k1m83ji9l1a7ng8a7v40psbymxasmssbrrhpdv2wl4rhs0nc3np"

["gopkg.in/yaml.v3"]
  sumVersion = "v3.0.0-20200313102051-9f266ea9e77c"
  ["gopkg.in/yaml.v3".fetch]
    type = "git"
    url = "https://gopkg.in/yaml.v3"
    rev = "9f266ea9e77c4c7aab4cf02650570e7c7b3031a5"
    sha256 = "1bbai3lzb50m0x2vwsdbagrbhvfylj9k1m32hgbqwldqx4p9ay35"
