name: "CI"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v17
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.8.0pre20220311_d532269/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            system-features = nixos-test benchmark big-parallel kvm recursive-nix

      - uses: cachix/cachix-action@v10
        with:
          name: zeek
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run Flake Show
        run: nix -Lv flake show

      - name: Eval Cells
        run: nix -Lv develop ./devshell -c eval-cells

      - name: Check Cliche Example
        run: nix develop ./devshell -c std run //cliche//entrypoints:example add 1 2

      - name: Check Comonicon Example
        run: nix develop ./devshell -c std run //comonicon//entrypoints:mycmd

      - name: Check schedulers of config
        run: nix develop ./devshell -c std run //schedulers//entrypoints:tenzir-config

      - name: Check DevShell Menu
        run: nix develop ./devshell -c menu
